#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/code/pengwynn/octokit

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=octokit

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n shell -t $SESSION

    tmux send-keys -t $SESSION:1 'vim' C-m

    # work around for renaming
    tmux rename-window -t $SESSION:2 shell

    tmux select-window -t $SESSION:1

    # pane for guard
    tmux split-window -h -p 30
    tmux send-keys -t $SESSION:1 'be guard' C-m

    # set status-left for guard
    tmux set status-left "◢◣"
  fi

  tmux attach -t $SESSION
}
load_session
