#!/bin/env bash

edit_pkg_file() {
  read -p "Edit now? (y/n)"
  if [ "$REPLY" == "y" ]; then
    $EDITOR "$PKG_FILE"
  else
    exit 1
  fi
}

ensure_pkg_file() {
  if [ ! -s "$PKG_FILE" ]; then
    mkdir -p $PKG_HOME
    touch $PKG_FILE
    echo "Package file not found... created."
    edit_pkg_file
  fi
}


print_pkg_count() {
  PKG_COUNT="$(cat $PKG_FILE | wc -l | xargs)"

  if [ $PKG_COUNT -eq 0  ];then
    echo "No $PKG_MGR packages to install"
  else
    echo "Installing $PKG_COUNT $PKG_MGR packages..."
  fi
}

PKG_FILE="$PKG_HOME/$PKG_MGR"

while getopts ":l" opt; do
  case ${opt} in
    l )
      cat "$PKG_FILE"
      ;;
  esac
done

if [ "$#" -ne 1  ]; then
  ensure_pkg_file
  print_pkg_count
fi

