#!/usr/bin/env bash
# Usage: pkg all
# Summary: List available package managers
# Help: This will print out when you run `sub help who`.
# You can have multiple lines even!
#
#    Show off an example indented
#
# And maybe start off another one?

set -e

for entry in $(ls $PKG_HOME); do
  echo $entry
done
