#!/usr/bin/env bash
# Usage: pkg node
# Summary: Install default Node modules
# Help: This will print out when you run `sub help who`.
# You can have multiple lines even!
#
#    Show off an example indented
#
# And maybe start off another one?

set -e

PKG_MGR="node"
source "$(dirname $0)/installer-functions"

if [ "$#" -ne 1  ]; then
  npm install --global $(cat $PKG_FILE | xargs)
fi
