#!/usr/bin/env bash
# Usage: pkg go
# Summary: Install default Ruby gems
# Help: This will print out when you run `sub help who`.
# You can have multiple lines even!
#
#    Show off an example indented
#
# And maybe start off another one?

set -e

PKG_MGR="go"
source "$(dirname $0)/installer-functions"

if [ "$#" -ne 1  ]; then
  for package in $(cat $PKG_FILE);do
    echo "Go go gadget ${package##*/}!"
    go get "$package"
  done
fi
