#!/usr/bin/env bash
# Usage: pkg brew
# Summary: Install Homebrew packages
# Help: This will print out when you run `sub help who`.
# You can have multiple lines even!
#
#    Show off an example indented
#
# And maybe start off another one?

set -e

PKG_MGR="brew"
source "$(dirname $0)/installer-functions"

if [ "$#" -ne 1  ]; then
  brew bundle "--file=$PKG_FILE"
fi
