#!/usr/bin/env ruby
# Usage: wynn status [all]
# Summary: Check GitHub system status
# Help: https://status.github.com/api
#
# encoding: utf-8
require 'json'

%w(json open-uri).each { |lib| require lib }

def display_status(status)
  color = case status['status']
          when 'good'
            "\e[32m"
          when 'minor'
            "\e[33m"
          when 'major'
            "\e[31m"
          end
  timestamp = Time.parse status['created_on']
  puts "#{timestamp.to_s} #{color}#{status['body']}\e[0m"
end

response = open("https://status.github.com/api/messages.json").read

statuses = JSON.parse(response)
if ARGV.first == 'all'
  statuses.each { |s| display_status s }
else
  display_status statuses.first
end
