#!/usr/bin/env bash
# Usage: wynn vanity
# Summary: Check Twitter followers count
# Help: Uses the t gem to check followers for a given Twitter user
#
#    wynn vanity [username]

set -e
USERNAME=${1:-"pengwynn"}
echo $USERNAME $(t user $USERNAME | grep Followers | cut -d " " -f 5)
