#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/code/pengwynn/blog

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=blog

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n shell -t $SESSION
    tmux new-window -n server -t $SESSION

    tmux send-keys -t $SESSION:1 'vim' C-m #':CtrlP' C-m
    tmux send-keys -t $SESSION:3 'shotgun -p 3076' C-m

    # work around for renaming
    tmux rename-window -t $SESSION:2 shell
    tmux rename-window -t $SESSION:3 server

    tmux select-window -t $SESSION:1
  fi

  tmux attach -t $SESSION
}
load_session
