#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/code/mobile/Memodex

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=memodex

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n shell -t $SESSION

    tmux send-keys -t $SESSION:1 'vim' C-m ':NERDTreeToggle' C-m

    tmux select-window -t $SESSION:1
  fi

  tmux attach -t $SESSION
}
load_session
