install ack
install cowsay
install figlet
install gawk
install grc
install hub
install imagemagick
install macvim --override-system-vim
install reattach-to-user-namespace
install the_silver_searcher
install tmux
install tree
install wget
install zsh

# quicklook plugins
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install qlprettypatch
cask install quicklook-csv
cask install betterzipql
cask install webp-quicklook

update
