#!/usr/bin/env bash
#
# Run all installers and symlink dotfiles

set -e

echo "Bootstrapping"

echo "Updating submodules"
git submodule init && git submodule update

script/platform
script/generic
script/symlinks
