#!/bin/sh
#
# Install a vim plugin as a git submodule
command -v hub >/dev/null 2>&1 || { echo >&2 "This command needs hub installed and in PATH. http://defunkt.io/hub"; exit 1; }

set -e

VIM_PLUGINS_PATH="vim/vim.symlink/bundle"

# Gets the command name without path
cmd(){ echo `basename $0`; }

# Help command output
usage(){
echo "\
`cmd` repository [destination module name]

Install a vim plugin as git submodule

Example: `cmd` tpope/vim-rails
"
}
[ $# -eq 0 ] && {
  usage
  exit 1
}


REMOTE_URL="$1"

if [[ -z $2 ]]; then
  SUBMODULE_PATH="$(echo $1 | cut -d/ -f2-)"
else
  SUBMODULE_PATH="$2"
fi

INSTALL_PATH="$VIM_PLUGINS_PATH/$SUBMODULE_PATH"

echo "Installing $REMOTE_URL to $INSTALL_PATH"

hub submodule add $REMOTE_URL $INSTALL_PATH
